### PR TITLE
Create CHANGELOG.md

### PR DESCRIPTION
**Pull request by fandok**

### CODE REVIEW

**Comment by irvantaufik28** [comment]
amazing

**Review by tofatoff — COMMENTED** [review]
lorem ipsum dolor sit amet

**Review by syafiq2408 — COMMENTED** [review]
Nyoba comment

**Comment by ramadhan8g** [comment]
ggmu mas

**Comment by mashitaad** [comment]
leave a comment

**Comment by khileab** [comment]
cool

**Review by syafiq2408 — APPROVED** [review]
Mantul

**Review by mashitaad — APPROVED** [review]
leave comment

**Comment by ramdhianty** [comment]
test

**Comment by sadi98** [comment]
test

**Review by artemiusbesta — APPROVED** [review]
mantap jiwa

**Comment by ramadhan8g** [comment]
aprove

**Comment by shrlhdyt** [comment]
mas

**Review by ramdhianty — APPROVED** [review]

**Comment by ibnasitinh** [comment]
zzz

**Pull request closed without merging**
